pipeline {
    agent any
    tools {
        nodejs 'nodejs-20.18.1'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: '<https://github.com/Nisha-Velmurugan/assessment2.git>'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}
